package middleware

import "testing"

// An operation the audit trail fails to recognise as a mutation is a
// state change that goes unrecorded, so the classifier is exercised
// against the shapes clients actually send.
func TestMutationName(t *testing.T) {
	cases := []struct {
		name          string
		operationName string
		query         string
		wantName      string
		wantMutation  bool
	}{
		{
			name:          "named mutation uses the operation name",
			operationName: "CreateProduct",
			query:         "mutation CreateProduct($input: CreateProductInput!) { createProduct(input: $input) { id } }",
			wantName:      "CreateProduct",
			wantMutation:  true,
		},
		{
			// gqlgen accepts an unnamed operation, so the document text
			// is the authority and the field name is the best label.
			name:         "anonymous mutation falls back to the first field",
			query:        "mutation { createProduct(input: {name: \"x\"}) { id } }",
			wantName:     "createProduct",
			wantMutation: true,
		},
		{
			name:         "anonymous mutation with no arguments",
			query:        "mutation { resetDemoData { ok } }",
			wantName:     "resetDemoData",
			wantMutation: true,
		},
		{
			name:         "leading whitespace and newlines",
			query:        "\n\n   mutation {\n  deleteProduct(id: \"1\") { id }\n}",
			wantName:     "deleteProduct",
			wantMutation: true,
		},
		{
			// A comment block before the keyword must not hide a mutation
			// from the audit trail.
			name:         "leading comment block",
			query:        "# generated by the admin client\n# do not edit\nmutation { archiveOrder(id: \"1\") { id } }",
			wantName:     "archiveOrder",
			wantMutation: true,
		},
		{
			name:         "query is not audited",
			query:        "query GetProducts { products { id } }",
			wantMutation: false,
		},
		{
			name:         "shorthand query is not audited",
			query:        "{ products { id } }",
			wantMutation: false,
		},
		{
			name:         "subscription is not a mutation",
			query:        "subscription { orderUpdated { id } }",
			wantMutation: false,
		},
		{
			name:         "empty document",
			query:        "",
			wantMutation: false,
		},
		{
			name:         "comment with no newline after it",
			query:        "# just a comment",
			wantMutation: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			gotName, gotMutation := mutationName(graphQLRequest{
				OperationName: tc.operationName,
				Query:         tc.query,
			})

			if gotMutation != tc.wantMutation {
				t.Fatalf("isMutation = %v, want %v", gotMutation, tc.wantMutation)
			}
			if tc.wantMutation && gotName != tc.wantName {
				t.Errorf("name = %q, want %q", gotName, tc.wantName)
			}
		})
	}
}

// firstSelection only ever produces a label for the audit row, so it
// degrades to the generic "mutation" rather than guessing. The row is
// still written either way.
func TestFirstSelection_Degenerate(t *testing.T) {
	cases := map[string]string{
		"mutation":       "mutation", // no selection set at all
		"mutation {":     "mutation", // truncated document
		"mutation {   }": "mutation", // empty selection set

		// The field name is only recognised when a delimiter follows it.
		// A closing brace is not one, so a field with neither arguments
		// nor a sub-selection falls back to the generic label.
		"mutation {createProduct}":  "mutation",
		"mutation {\n\tcreateOrder": "mutation",

		// The shapes real clients send, which all carry a delimiter.
		"mutation { createProduct(input: {}) { id } }":    "createProduct",
		"mutation {\n  archiveOrder(id: \"1\") { id }\n}": "archiveOrder",
	}

	for query, want := range cases {
		t.Run(query, func(t *testing.T) {
			if got := firstSelection(query); got != want {
				t.Errorf("firstSelection(%q) = %q, want %q", query, got, want)
			}
		})
	}
}

func TestAuditNullable(t *testing.T) {
	if got := nullable(""); got != nil {
		t.Errorf("nullable(\"\") = %v, want nil", got)
	}
	if got := nullable("tenant-1"); got != "tenant-1" {
		t.Errorf("nullable(%q) = %v, want %q", "tenant-1", got, "tenant-1")
	}
}
