// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int32  `json:"expiresIn"`
	User         *User  `json:"user"`
}

type CannedResponse struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Shortcut *string   `json:"shortcut,omitempty"`
	Body     string    `json:"body"`
}

type CreateCampaignInput struct {
	Name       string    `json:"name"`
	Subject    string    `json:"subject"`
	TemplateID uuid.UUID `json:"templateId"`
}

type CreateProductInput struct {
	Name         string   `json:"name"`
	Description  *string  `json:"description,omitempty"`
	BasePrice    float64  `json:"basePrice"`
	ComparePrice *float64 `json:"comparePrice,omitempty"`
	Tags         []string `json:"tags,omitempty"`
}

type CreateTicketInput struct {
	Subject       string     `json:"subject"`
	Body          string     `json:"body"`
	CustomerEmail string     `json:"customerEmail"`
	CustomerName  *string    `json:"customerName,omitempty"`
	Source        *string    `json:"source,omitempty"`
	Priority      *string    `json:"priority,omitempty"`
	OrderID       *uuid.UUID `json:"orderId,omitempty"`
}

type EmailCampaign struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Subject        string     `json:"subject"`
	TemplateID     *uuid.UUID `json:"templateId,omitempty"`
	Status         string     `json:"status"`
	RecipientType  string     `json:"recipientType"`
	RecipientCount int32      `json:"recipientCount"`
	SentCount      int32      `json:"sentCount"`
	DeliveredCount int32      `json:"deliveredCount"`
	OpenedCount    int32      `json:"openedCount"`
	ClickedCount   int32      `json:"clickedCount"`
	ScheduledAt    *time.Time `json:"scheduledAt,omitempty"`
	StartedAt      *time.Time `json:"startedAt,omitempty"`
	CompletedAt    *time.Time `json:"completedAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type EmailTemplate struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description,omitempty"`
	Subject     string    `json:"subject"`
	IsSystem    bool      `json:"isSystem"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Order struct {
	ID            uuid.UUID    `json:"id"`
	Status        string       `json:"status"`
	Total         float64      `json:"total"`
	CustomerEmail string       `json:"customerEmail"`
	CustomerName  *string      `json:"customerName,omitempty"`
	Items         []*OrderItem `json:"items"`
	CreatedAt     time.Time    `json:"createdAt"`
	PaidAt        *time.Time   `json:"paidAt,omitempty"`
}

type OrderItem struct {
	ID           uuid.UUID `json:"id"`
	ProductName  string    `json:"productName"`
	VariantTitle string    `json:"variantTitle"`
	Quantity     int32     `json:"quantity"`
	UnitPrice    float64   `json:"unitPrice"`
	TotalPrice   float64   `json:"totalPrice"`
	ImageURL     *string   `json:"imageUrl,omitempty"`
}

type Product struct {
	ID           uuid.UUID         `json:"id"`
	TenantID     uuid.UUID         `json:"tenantId"`
	Name         string            `json:"name"`
	Slug         string            `json:"slug"`
	Description  *string           `json:"description,omitempty"`
	ShortDesc    *string           `json:"shortDesc,omitempty"`
	BasePrice    float64           `json:"basePrice"`
	ComparePrice *float64          `json:"comparePrice,omitempty"`
	Status       string            `json:"status"`
	IsFeatured   bool              `json:"isFeatured"`
	Tags         []string          `json:"tags"`
	Images       []*ProductImage   `json:"images"`
	Variants     []*ProductVariant `json:"variants"`
	CreatedAt    time.Time         `json:"createdAt"`
	UpdatedAt    time.Time         `json:"updatedAt"`
}

type ProductImage struct {
	ID       uuid.UUID `json:"id"`
	URL      string    `json:"url"`
	AltText  *string   `json:"altText,omitempty"`
	Position int32     `json:"position"`
}

type ProductVariant struct {
	ID            uuid.UUID `json:"id"`
	Sku           string    `json:"sku"`
	Title         string    `json:"title"`
	Option1Name   *string   `json:"option1Name,omitempty"`
	Option1Value  *string   `json:"option1Value,omitempty"`
	Option2Name   *string   `json:"option2Name,omitempty"`
	Option2Value  *string   `json:"option2Value,omitempty"`
	Price         float64   `json:"price"`
	ComparePrice  *float64  `json:"comparePrice,omitempty"`
	StockQuantity int32     `json:"stockQuantity"`
	IsInStock     bool      `json:"isInStock"`
	IsActive      bool      `json:"isActive"`
	ImageURL      *string   `json:"imageUrl,omitempty"`
}

type Query struct {
}

type SupportMetrics struct {
	OpenTickets           int32                `json:"openTickets"`
	AvgFirstResponseHours float64              `json:"avgFirstResponseHours"`
	AvgResolutionHours    float64              `json:"avgResolutionHours"`
	SLABreachRate         float64              `json:"slaBreachRate"`
	TicketsByDay          []*TicketsByDay      `json:"ticketsByDay"`
	TicketsByStatus       []*TicketsByStatus   `json:"ticketsByStatus"`
	TicketsByPriority     []*TicketsByPriority `json:"ticketsByPriority"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Subdomain string    `json:"subdomain"`
	Plan      string    `json:"plan"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
}

type Ticket struct {
	ID                 uuid.UUID        `json:"id"`
	Number             int32            `json:"number"`
	Subject            string           `json:"subject"`
	Status             string           `json:"status"`
	Priority           string           `json:"priority"`
	CustomerEmail      string           `json:"customerEmail"`
	CustomerName       *string          `json:"customerName,omitempty"`
	AssigneeID         *uuid.UUID       `json:"assigneeId,omitempty"`
	AssigneeName       string           `json:"assigneeName"`
	Source             string           `json:"source"`
	SLAStatus          string           `json:"slaStatus"`
	SLAFirstResponseAt *time.Time       `json:"slaFirstResponseAt,omitempty"`
	FirstResponseAt    *time.Time       `json:"firstResponseAt,omitempty"`
	ResolvedAt         *time.Time       `json:"resolvedAt,omitempty"`
	AiDraftBody        *string          `json:"aiDraftBody,omitempty"`
	AiDraftConfidence  *float64         `json:"aiDraftConfidence,omitempty"`
	LatestMessage      string           `json:"latestMessage"`
	UnreadCount        int32            `json:"unreadCount"`
	Messages           []*TicketMessage `json:"messages"`
	CreatedAt          time.Time        `json:"createdAt"`
	UpdatedAt          time.Time        `json:"updatedAt"`
}

type TicketMessage struct {
	ID          uuid.UUID `json:"id"`
	AuthorType  string    `json:"authorType"`
	AuthorName  *string   `json:"authorName,omitempty"`
	AuthorEmail *string   `json:"authorEmail,omitempty"`
	Body        string    `json:"body"`
	IsInternal  bool      `json:"isInternal"`
	CreatedAt   time.Time `json:"createdAt"`
}

type TicketsByDay struct {
	Date  string `json:"date"`
	Count int32  `json:"count"`
}

type TicketsByPriority struct {
	Priority string `json:"priority"`
	Count    int32  `json:"count"`
}

type TicketsByStatus struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

type UpdateProductInput struct {
	Name         *string  `json:"name,omitempty"`
	Description  *string  `json:"description,omitempty"`
	BasePrice    *float64 `json:"basePrice,omitempty"`
	ComparePrice *float64 `json:"comparePrice,omitempty"`
	Status       *string  `json:"status,omitempty"`
	IsFeatured   *bool    `json:"isFeatured,omitempty"`
	Tags         []string `json:"tags,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName *string   `json:"firstName,omitempty"`
	LastName  *string   `json:"lastName,omitempty"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}
