package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"

	"github.com/hellohirusha/ownstall/graph/model"
	appMiddleware "github.com/hellohirusha/ownstall/internal/middleware"
)

// UpdateStoreProfile edits the seller's own listing details.
func (r *mutationResolver) UpdateStoreProfile(ctx context.Context, input model.StoreProfileInput) (*model.Store, error) {
	tenantID, err := requireTenant(ctx)
	if err != nil {
		return nil, err
	}

	// Three-way per field: NULL (omitted) leaves it untouched, an empty
	// string clears it, anything else sets it. A plain COALESCE would give
	// only the first two-thirds — a seller could never remove a tagline or
	// swap out a logo once one had been set.
	//
	// The name is the exception: a stall must always have one, so an empty
	// name is treated as "leave it alone" rather than "erase it".
	_, err = r.DB.Exec(ctx, `
        UPDATE tenants SET
            name        = COALESCE(NULLIF($2, ''), name),
            tagline     = CASE WHEN $3::text IS NULL THEN tagline     WHEN $3 = '' THEN NULL ELSE $3 END,
            description = CASE WHEN $4::text IS NULL THEN description WHEN $4 = '' THEN NULL ELSE $4 END,
            category    = CASE WHEN $5::text IS NULL THEN category    WHEN $5 = '' THEN NULL ELSE $5 END,
            location    = CASE WHEN $6::text IS NULL THEN location    WHEN $6 = '' THEN NULL ELSE $6 END,
            logo_url    = CASE WHEN $7::text IS NULL THEN logo_url    WHEN $7 = '' THEN NULL ELSE $7 END
        WHERE id = $1
    `, tenantID, derefOr(input.Name, ""), input.Tagline, input.Description,
		input.Category, input.Location, input.LogoURL)
	if err != nil {
		return nil, fmt.Errorf("failed to update stall: %w", err)
	}

	return r.fetchStore(ctx, "t.id = $1", tenantID)
}

// SubmitStoreForReview puts a pending or rejected stall into the queue.
func (r *mutationResolver) SubmitStoreForReview(ctx context.Context) (*model.Store, error) {
	tenantID, err := requireTenant(ctx)
	if err != nil {
		return nil, err
	}

	var status string
	if err := r.DB.QueryRow(ctx,
		`SELECT status FROM tenants WHERE id = $1`, tenantID,
	).Scan(&status); err != nil {
		return nil, fmt.Errorf("stall not found")
	}

	switch status {
	case "approved":
		return nil, fmt.Errorf("this stall is already approved")
	case "suspended":
		return nil, fmt.Errorf("suspended stalls cannot be resubmitted — contact support")
	}

	if _, err := r.DB.Exec(ctx, `
        UPDATE tenants
           SET status = 'pending', submitted_at = NOW(), review_note = NULL
         WHERE id = $1
    `, tenantID); err != nil {
		return nil, fmt.Errorf("failed to submit stall: %w", err)
	}

	if err := r.recordModeration(ctx, tenantID, "", "submit", nil); err != nil {
		return nil, fmt.Errorf("failed to record submission: %w", err)
	}

	return r.fetchStore(ctx, "t.id = $1", tenantID)
}

// AcceptTerms records the seller's acceptance of a specific terms version.
func (r *mutationResolver) AcceptTerms(ctx context.Context, version string) (bool, error) {
	tenantID, err := requireTenant(ctx)
	if err != nil {
		return false, err
	}

	version = strings.TrimSpace(version)
	if version == "" {
		return false, fmt.Errorf("a terms version is required")
	}

	userID := appMiddleware.GetUserID(ctx)
	var userIDArg any
	if userID != "" {
		userIDArg = userID
	}

	if _, err := r.DB.Exec(ctx, `
        INSERT INTO terms_acceptances (tenant_id, user_id, version)
        VALUES ($1, $2, $3)
    `, tenantID, userIDArg, version); err != nil {
		return false, fmt.Errorf("failed to record acceptance: %w", err)
	}

	return true, nil
}

// ApproveStore is the resolver for the approveStore field.
func (r *mutationResolver) ApproveStore(ctx context.Context, tenantID uuid.UUID, note *string) (*model.Store, error) {
	return r.moderate(ctx, tenantID.String(), "approve", "approved", note)
}

// RejectStore is the resolver for the rejectStore field.
func (r *mutationResolver) RejectStore(ctx context.Context, tenantID uuid.UUID, reason string) (*model.Store, error) {
	return r.moderate(ctx, tenantID.String(), "reject", "rejected", &reason)
}

// SuspendStore is the resolver for the suspendStore field.
func (r *mutationResolver) SuspendStore(ctx context.Context, tenantID uuid.UUID, reason string) (*model.Store, error) {
	return r.moderate(ctx, tenantID.String(), "suspend", "suspended", &reason)
}

// RestoreStore is the resolver for the restoreStore field.
func (r *mutationResolver) RestoreStore(ctx context.Context, tenantID uuid.UUID) (*model.Store, error) {
	return r.moderate(ctx, tenantID.String(), "restore", "approved", nil)
}

// SetStoreRestrictions is the lighter alternative to suspension: the stall
// stays listed but loses a specific capability.
func (r *mutationResolver) SetStoreRestrictions(ctx context.Context, tenantID uuid.UUID, canPublishProducts bool, canAcceptOrders bool, reason *string) (*model.Store, error) {
	adminID, err := requireAdmin(ctx)
	if err != nil {
		return nil, err
	}

	id := tenantID.String()

	action := "restrict"
	if canPublishProducts && canAcceptOrders {
		action = "unrestrict"
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	tag, err := tx.Exec(ctx, `
        UPDATE tenants
           SET can_publish_products = $2, can_accept_orders = $3
         WHERE id = $1
    `, id, canPublishProducts, canAcceptOrders)
	if err != nil {
		return nil, fmt.Errorf("failed to update restrictions: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return nil, fmt.Errorf("stall not found")
	}

	if _, err := tx.Exec(ctx, `
        INSERT INTO tenant_moderation_events (tenant_id, admin_id, action, reason)
        VALUES ($1, $2, $3, $4)
    `, id, adminID, action, reason); err != nil {
		return nil, fmt.Errorf("failed to record moderation: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	return r.fetchStore(ctx, "t.id = $1", id)
}

// Stores is the public stall directory. It only ever returns approved, active
// stalls — an unapproved or suspended stall must not be discoverable.
func (r *queryResolver) Stores(ctx context.Context, input *model.StoreSearchInput) (*model.StoreSearchResult, error) {
	if input == nil {
		input = &model.StoreSearchInput{}
	}

	// Bound the page size so a caller cannot ask for the whole table.
	limit := int32(24)
	if input.Limit != nil && *input.Limit > 0 && *input.Limit <= 100 {
		limit = *input.Limit
	}
	offset := int32(0)
	if input.Offset != nil && *input.Offset > 0 {
		offset = *input.Offset
	}

	where := []string{"t.status = 'approved'", "t.is_active = true"}
	args := []any{}

	if input.Search != nil && strings.TrimSpace(*input.Search) != "" {
		args = append(args, "%"+strings.TrimSpace(*input.Search)+"%")
		where = append(where, fmt.Sprintf(
			`(t.name ILIKE $%d OR t.tagline ILIKE $%d OR t.description ILIKE $%d
			  OR t.subdomain ILIKE $%d OR t.category ILIKE $%d
			  OR EXISTS (SELECT 1 FROM products p
			              WHERE p.tenant_id = t.id AND p.status = 'active'
			                AND p.name ILIKE $%d))`,
			len(args), len(args), len(args), len(args), len(args), len(args),
		))
	}

	if input.Category != nil && strings.TrimSpace(*input.Category) != "" {
		args = append(args, strings.TrimSpace(*input.Category))
		where = append(where, fmt.Sprintf("t.category = $%d", len(args)))
	}

	whereSQL := strings.Join(where, " AND ")

	// Whitelist the sort: this lands in the SQL string, so it can never be
	// taken from the caller verbatim.
	orderBy := "t.created_at DESC"
	if input.Sort != nil {
		switch *input.Sort {
		case "oldest":
			orderBy = "t.created_at ASC"
		case "name":
			orderBy = "t.name ASC"
		case "products":
			orderBy = `(SELECT COUNT(*) FROM products p
			             WHERE p.tenant_id = t.id AND p.status = 'active') DESC`
		}
	}

	var total int32
	if err := r.DB.QueryRow(ctx,
		"SELECT COUNT(*) FROM tenants t WHERE "+whereSQL, args...,
	).Scan(&total); err != nil {
		return nil, fmt.Errorf("failed to count stalls: %w", err)
	}

	query := fmt.Sprintf(
		"SELECT %s FROM tenants t WHERE %s ORDER BY %s LIMIT $%d OFFSET $%d",
		storeColumns, whereSQL, orderBy, len(args)+1, len(args)+2,
	)
	args = append(args, limit, offset)

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to search stalls: %w", err)
	}
	defer rows.Close()

	result := &model.StoreSearchResult{Stores: []*model.Store{}, Total: total}
	for rows.Next() {
		store, err := scanStore(rows)
		if err != nil {
			return nil, fmt.Errorf("failed to scan stall: %w", err)
		}
		result.Stores = append(result.Stores, store)
	}
	return result, rows.Err()
}

// StoreCategories powers the directory's category filter. Only categories that
// actually have an approved stall behind them are offered.
func (r *queryResolver) StoreCategories(ctx context.Context) ([]*model.CategoryCount, error) {
	rows, err := r.DB.Query(ctx, `
        SELECT category, COUNT(*)
        FROM tenants
        WHERE status = 'approved' AND is_active = true
          AND category IS NOT NULL AND category <> ''
        GROUP BY category
        ORDER BY COUNT(*) DESC, category ASC
    `)
	if err != nil {
		return nil, fmt.Errorf("failed to load categories: %w", err)
	}
	defer rows.Close()

	result := []*model.CategoryCount{}
	for rows.Next() {
		var c model.CategoryCount
		var count int32
		if err := rows.Scan(&c.Category, &count); err != nil {
			return nil, err
		}
		c.Count = count
		result = append(result, &c)
	}
	return result, rows.Err()
}

// Store is the public lookup for one stall.
func (r *queryResolver) Store(ctx context.Context, subdomain string) (*model.Store, error) {
	store, err := r.fetchStore(ctx,
		"t.subdomain = $1 AND t.status = 'approved' AND t.is_active = true",
		strings.ToLower(strings.TrimSpace(subdomain)))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return store, nil
}

// MyOrders is the signed-in shopper's order history across every stall.
//
// Orders are matched on buyer_id, plus any guest order placed with the same
// email address before the account existed — otherwise signing up would
// appear to erase the orders that prompted you to sign up.
func (r *queryResolver) MyOrders(ctx context.Context) ([]*model.BuyerOrder, error) {
	buyerID, err := requireBuyer(ctx)
	if err != nil {
		return nil, err
	}

	rows, err := r.DB.Query(ctx, `
        SELECT o.id, t.name, t.subdomain, o.status, o.total,
               o.customer_email, o.tracking_number, o.created_at
        FROM orders o
        JOIN tenants t ON t.id = o.tenant_id
        WHERE o.buyer_id = $1
           OR (o.buyer_id IS NULL
               AND lower(o.customer_email) = (SELECT lower(email) FROM buyers WHERE id = $1))
        ORDER BY o.created_at DESC
    `, buyerID)
	if err != nil {
		return nil, fmt.Errorf("failed to load orders: %w", err)
	}
	defer rows.Close()

	orders := []*model.BuyerOrder{}
	ids := []string{}
	byID := map[string]*model.BuyerOrder{}

	for rows.Next() {
		var o model.BuyerOrder
		var id string
		if err := rows.Scan(
			&id, &o.StoreName, &o.StoreSubdomain, &o.Status, &o.Total,
			&o.CustomerEmail, &o.TrackingNumber, &o.CreatedAt,
		); err != nil {
			return nil, err
		}
		o.ID = parseUUID(id)
		o.Items = []*model.BuyerOrderItem{}
		orders = append(orders, &o)
		ids = append(ids, id)
		byID[id] = &o
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if len(ids) == 0 {
		return orders, nil
	}

	// One query for every order's items rather than one per order.
	itemRows, err := r.DB.Query(ctx, `
        SELECT order_id, product_name, variant_title, quantity, total_price, image_url
        FROM order_items
        WHERE order_id = ANY($1::uuid[])
        ORDER BY created_at ASC
    `, ids)
	if err != nil {
		return nil, fmt.Errorf("failed to load order items: %w", err)
	}
	defer itemRows.Close()

	for itemRows.Next() {
		var orderID string
		var item model.BuyerOrderItem
		var quantity int32
		if err := itemRows.Scan(
			&orderID, &item.ProductName, &item.VariantTitle,
			&quantity, &item.TotalPrice, &item.ImageURL,
		); err != nil {
			return nil, err
		}
		item.Quantity = quantity
		if order, ok := byID[orderID]; ok {
			order.Items = append(order.Items, &item)
		}
	}

	return orders, itemRows.Err()
}

// MyStore returns the signed-in seller's stall, including review state. Unlike
// the public `store` query this does not filter on status — the whole point is
// to tell a seller their stall is still pending or has been rejected.
func (r *queryResolver) MyStore(ctx context.Context) (*model.Store, error) {
	tenantID, err := requireTenant(ctx)
	if err != nil {
		return nil, err
	}

	store, err := r.fetchStore(ctx, "t.id = $1", tenantID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return store, nil
}

// PlatformStats is the resolver for the platformStats field.
func (r *queryResolver) PlatformStats(ctx context.Context) (*model.PlatformStats, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	var s model.PlatformStats
	err := r.DB.QueryRow(ctx, `
        SELECT
            (SELECT COUNT(*) FROM tenants),
            (SELECT COUNT(*) FROM tenants WHERE status = 'pending'),
            (SELECT COUNT(*) FROM tenants WHERE status = 'approved'),
            (SELECT COUNT(*) FROM tenants WHERE status = 'suspended'),
            (SELECT COUNT(*) FROM tenants WHERE status = 'rejected'),
            (SELECT COUNT(*) FROM products),
            (SELECT COUNT(*) FROM orders),
            (SELECT COUNT(*) FROM orders WHERE status <> 'pending' AND status <> 'failed'),
            (SELECT COALESCE(SUM(total), 0) FROM orders
              WHERE status NOT IN ('pending', 'failed', 'cancelled', 'refunded')),
            (SELECT COUNT(*) FROM buyers)
    `).Scan(
		&s.TotalStores, &s.PendingStores, &s.ApprovedStores,
		&s.SuspendedStores, &s.RejectedStores,
		&s.TotalProducts, &s.TotalOrders, &s.PaidOrders,
		&s.GrossRevenue, &s.TotalBuyers,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to load platform stats: %w", err)
	}
	return &s, nil
}

// AdminStores lists stalls in any state — this is the moderation queue.
func (r *queryResolver) AdminStores(ctx context.Context, status *string, search *string, limit *int32, offset *int32) ([]*model.Store, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	pageSize := int32(50)
	if limit != nil && *limit > 0 && *limit <= 200 {
		pageSize = *limit
	}
	skip := int32(0)
	if offset != nil && *offset > 0 {
		skip = *offset
	}

	where := []string{"TRUE"}
	args := []any{}

	if status != nil && strings.TrimSpace(*status) != "" {
		args = append(args, strings.TrimSpace(*status))
		where = append(where, fmt.Sprintf("t.status = $%d", len(args)))
	}
	if search != nil && strings.TrimSpace(*search) != "" {
		args = append(args, "%"+strings.TrimSpace(*search)+"%")
		where = append(where, fmt.Sprintf(
			"(t.name ILIKE $%d OR t.subdomain ILIKE $%d)", len(args), len(args)))
	}

	query := fmt.Sprintf(`
        SELECT %s FROM tenants t
        WHERE %s
        -- Pending first: the queue is the reason this page exists
        ORDER BY (t.status = 'pending') DESC, t.submitted_at DESC NULLS LAST, t.created_at DESC
        LIMIT $%d OFFSET $%d`,
		storeColumns, strings.Join(where, " AND "), len(args)+1, len(args)+2)
	args = append(args, pageSize, skip)

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to list stalls: %w", err)
	}
	defer rows.Close()

	result := []*model.Store{}
	for rows.Next() {
		store, err := scanStore(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, store)
	}
	return result, rows.Err()
}

// StoreModerationHistory is the resolver for the storeModerationHistory field.
func (r *queryResolver) StoreModerationHistory(ctx context.Context, tenantID uuid.UUID) ([]*model.ModerationEvent, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	rows, err := r.DB.Query(ctx, `
        SELECT e.id, e.action, e.reason, a.email, e.created_at
        FROM tenant_moderation_events e
        LEFT JOIN platform_admins a ON a.id = e.admin_id
        WHERE e.tenant_id = $1
        ORDER BY e.created_at DESC
    `, tenantID.String())
	if err != nil {
		return nil, fmt.Errorf("failed to load moderation history: %w", err)
	}
	defer rows.Close()

	result := []*model.ModerationEvent{}
	for rows.Next() {
		var e model.ModerationEvent
		var id string
		if err := rows.Scan(&id, &e.Action, &e.Reason, &e.AdminEmail, &e.CreatedAt); err != nil {
			return nil, err
		}
		e.ID = parseUUID(id)
		result = append(result, &e)
	}
	return result, rows.Err()
}
