package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/hellohirusha/ownstall/graph/model"
	appMiddleware "github.com/hellohirusha/ownstall/internal/middleware"
	"github.com/hellohirusha/ownstall/internal/services"
	pgx "github.com/jackc/pgx/v5"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, storeName string, subdomain string, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// CreateProduct creates a new product for the authenticated tenant
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	p, err := r.ProductService.CreateProduct(ctx, services.CreateProductInput{
		TenantID:    tenantID,
		Name:        input.Name,
		Description: stringValue(input.Description),
		BasePrice:   input.BasePrice,
		Tags:        input.Tags,
	})
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input model.UpdateProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// PublishProduct sets a product's status to active for the authenticated tenant
func (r *mutationResolver) PublishProduct(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	p, err := r.ProductService.PublishProduct(ctx, tenantID, id.String())
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// AddProductImage attaches an uploaded image URL to one of the tenant's products
func (r *mutationResolver) AddProductImage(ctx context.Context, productID uuid.UUID, url string, altText *string) (*model.ProductImage, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	// The join against products enforces tenant ownership; position is
	// appended so the first image added becomes the primary (position 0)
	var id string
	var position int32
	err := r.DB.QueryRow(ctx, `
        INSERT INTO product_images (product_id, url, alt_text, position)
        SELECT p.id, $2, $3,
               COALESCE((SELECT MAX(position) + 1 FROM product_images WHERE product_id = p.id), 0)
        FROM products p
        WHERE p.id = $1 AND p.tenant_id = $4
        RETURNING id, position
    `, productID.String(), url, altText, tenantID).Scan(&id, &position)
	if err != nil {
		return nil, fmt.Errorf("failed to add product image: %w", err)
	}

	return &model.ProductImage{
		ID:       parseUUID(id),
		URL:      url,
		AltText:  altText,
		Position: position,
	}, nil
}

// CreateCampaign creates a draft campaign from one of the tenant's templates
func (r *mutationResolver) CreateCampaign(ctx context.Context, input model.CreateCampaignInput) (*model.EmailCampaign, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	// The join enforces that the template belongs to this tenant
	var id string
	err := r.DB.QueryRow(ctx, `
        INSERT INTO email_campaigns (tenant_id, template_id, name, subject, recipient_type, status)
        SELECT $1, t.id, $3, $4, 'all', 'draft'
        FROM email_templates t
        WHERE t.id = $2 AND t.tenant_id = $1
        RETURNING id
    `, tenantID, input.TemplateID.String(), input.Name, input.Subject).Scan(&id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("template not found")
		}
		return nil, fmt.Errorf("failed to create campaign: %w", err)
	}

	return r.fetchCampaign(ctx, tenantID, id)
}

// ScheduleCampaign queues a draft campaign for the scheduler.
// sendAt omitted/nil = due immediately (picked up on the next tick).
func (r *mutationResolver) ScheduleCampaign(ctx context.Context, id uuid.UUID, sendAt *time.Time) (*model.EmailCampaign, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	tag, err := r.DB.Exec(ctx, `
        UPDATE email_campaigns
        SET status = 'scheduled', scheduled_at = COALESCE($3, NOW())
        WHERE id = $1 AND tenant_id = $2 AND status IN ('draft', 'scheduled')
    `, id.String(), tenantID, sendAt)
	if err != nil {
		return nil, fmt.Errorf("failed to schedule campaign: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return nil, fmt.Errorf("campaign not found or already sending")
	}

	return r.fetchCampaign(ctx, tenantID, id.String())
}

// CreateTicket opens a support ticket for the authenticated tenant
func (r *mutationResolver) CreateTicket(ctx context.Context, input model.CreateTicketInput) (*model.Ticket, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	in := services.CreateTicketInput{
		TenantID:      tenantID,
		Subject:       input.Subject,
		Body:          input.Body,
		CustomerEmail: input.CustomerEmail,
		Source:        "web",
	}
	if input.CustomerName != nil {
		in.CustomerName = *input.CustomerName
	}
	if input.Source != nil && *input.Source != "" {
		in.Source = *input.Source
	}
	if input.Priority != nil {
		in.Priority = *input.Priority
	}
	if input.OrderID != nil {
		in.OrderID = input.OrderID.String()
	}

	ticket, err := r.TicketService.CreateTicket(ctx, in)
	if err != nil {
		return nil, err
	}
	return ticketToGraphQL(ticket), nil
}

// ReplyToTicket adds a staff reply or internal note to a tenant-owned ticket
func (r *mutationResolver) ReplyToTicket(ctx context.Context, ticketID uuid.UUID, body string, isInternal bool) (*model.TicketMessage, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	userID := appMiddleware.GetUserID(ctx)
	if tenantID == "" || userID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	// The service writes by ticket id alone — verify ownership first
	var owned bool
	if err := r.DB.QueryRow(ctx,
		"SELECT EXISTS(SELECT 1 FROM tickets WHERE id = $1 AND tenant_id = $2)",
		ticketID.String(), tenantID,
	).Scan(&owned); err != nil {
		return nil, fmt.Errorf("failed to verify ticket: %w", err)
	}
	if !owned {
		return nil, fmt.Errorf("ticket not found")
	}

	msg, err := r.TicketService.ReplyToTicket(ctx, services.ReplyInput{
		TenantID:   tenantID,
		TicketID:   ticketID.String(),
		AuthorID:   userID,
		Body:       body,
		IsInternal: isInternal,
	})
	if err != nil {
		return nil, err
	}
	return ticketMessageToGraphQL(msg), nil
}

// UpdateTicketStatus changes a ticket's status and returns the updated ticket
func (r *mutationResolver) UpdateTicketStatus(ctx context.Context, ticketID uuid.UUID, status string) (*model.Ticket, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	userID := appMiddleware.GetUserID(ctx)
	if tenantID == "" || userID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	if err := r.TicketService.UpdateTicketStatus(ctx, tenantID, ticketID.String(), userID, status); err != nil {
		return nil, fmt.Errorf("failed to update ticket status: %w", err)
	}

	ticket, err := r.TicketService.GetTicketWithMessages(ctx, tenantID, ticketID.String())
	if err != nil {
		return nil, err
	}
	return ticketToGraphQL(ticket), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Tenant looks up a store by its subdomain (public storefront entry point)
func (r *queryResolver) Tenant(ctx context.Context, subdomain string) (*model.Tenant, error) {
	var t model.Tenant
	var id string
	err := r.DB.QueryRow(ctx, `
        SELECT id, name, subdomain, plan, is_active, created_at
        FROM tenants
        WHERE subdomain = $1 AND is_active = true
    `, subdomain).Scan(&id, &t.Name, &t.Subdomain, &t.Plan, &t.IsActive, &t.CreatedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Unknown subdomain — the schema allows a null tenant
			return nil, nil
		}
		return nil, err
	}

	t.ID = parseUUID(id)
	return &t, nil
}

// Products lists the authenticated tenant's products, or — when tenantId is
// given (public storefront) — another tenant's active products only
func (r *queryResolver) Products(ctx context.Context, tenantID *uuid.UUID, status *string) ([]*model.Product, error) {
	tenant := appMiddleware.GetTenantID(ctx)

	statusFilter := ""
	if status != nil {
		statusFilter = *status
	}

	if tenantID != nil {
		// Never expose another tenant's drafts to public callers
		if tenantID.String() != tenant {
			statusFilter = "active"
		}
		tenant = tenantID.String()
	}

	if tenant == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	products, err := r.ProductService.ListProducts(ctx, tenant, statusFilter)
	if err != nil {
		return nil, err
	}

	// Convert models to GraphQL types
	var result []*model.Product
	for _, p := range products {
		result = append(result, modelToGraphQL(p))
	}
	return result, nil
}

// Product fetches a single product (with images and variants) for the tenant
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	p, err := r.ProductService.GetProduct(ctx, tenantID, id)
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// ProductBySlug fetches a product by URL slug for the public storefront
func (r *queryResolver) ProductBySlug(ctx context.Context, tenantID uuid.UUID, slug string) (*model.Product, error) {
	p, err := r.ProductService.GetProductBySlug(ctx, tenantID.String(), slug)
	if err != nil {
		return nil, err
	}

	// Public callers only see active products
	if p.Status != "active" {
		return nil, nil
	}

	return modelToGraphQL(p), nil
}

// Orders lists the authenticated tenant's orders, newest first
func (r *queryResolver) Orders(ctx context.Context, status *string) ([]*model.Order, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	query := `
        SELECT id, status, total, customer_email, customer_name, created_at, paid_at
        FROM orders
        WHERE tenant_id = $1`
	args := []interface{}{tenantID}
	if status != nil && *status != "" {
		query += " AND status = $2"
		args = append(args, *status)
	}
	query += " ORDER BY created_at DESC"

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to query orders: %w", err)
	}
	defer rows.Close()

	var orders []*model.Order
	index := make(map[string]*model.Order)
	var ids []string
	for rows.Next() {
		var o model.Order
		var id string
		if err := rows.Scan(
			&id, &o.Status, &o.Total, &o.CustomerEmail, &o.CustomerName,
			&o.CreatedAt, &o.PaidAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan order row: %w", err)
		}
		o.ID = parseUUID(id)
		orders = append(orders, &o)
		index[id] = &o
		ids = append(ids, id)
	}

	if len(ids) == 0 {
		return orders, nil
	}

	// Batch-load items for all listed orders to avoid N+1 queries
	itemRows, err := r.DB.Query(ctx, `
        SELECT id, order_id, product_name, variant_title, quantity,
               unit_price, total_price, image_url
        FROM order_items
        WHERE order_id = ANY($1::uuid[])
        ORDER BY created_at ASC
    `, ids)
	if err != nil {
		return nil, fmt.Errorf("failed to query order items: %w", err)
	}
	defer itemRows.Close()

	for itemRows.Next() {
		var it model.OrderItem
		var id, orderID string
		if err := itemRows.Scan(
			&id, &orderID, &it.ProductName, &it.VariantTitle, &it.Quantity,
			&it.UnitPrice, &it.TotalPrice, &it.ImageURL,
		); err != nil {
			return nil, fmt.Errorf("failed to scan order item row: %w", err)
		}
		it.ID = parseUUID(id)
		if o, ok := index[orderID]; ok {
			o.Items = append(o.Items, &it)
		}
	}

	return orders, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// EmailTemplates lists the authenticated tenant's email templates
func (r *queryResolver) EmailTemplates(ctx context.Context) ([]*model.EmailTemplate, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	rows, err := r.DB.Query(ctx, `
        SELECT id, name, slug, description, subject, is_system, created_at
        FROM email_templates
        WHERE tenant_id = $1
        ORDER BY created_at ASC, name ASC
    `, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to query templates: %w", err)
	}
	defer rows.Close()

	var templates []*model.EmailTemplate
	for rows.Next() {
		var t model.EmailTemplate
		var id string
		if err := rows.Scan(&id, &t.Name, &t.Slug, &t.Description, &t.Subject, &t.IsSystem, &t.CreatedAt); err != nil {
			return nil, fmt.Errorf("failed to scan template row: %w", err)
		}
		t.ID = parseUUID(id)
		templates = append(templates, &t)
	}
	return templates, nil
}

// EmailCampaigns lists the authenticated tenant's campaigns with live stats
func (r *queryResolver) EmailCampaigns(ctx context.Context) ([]*model.EmailCampaign, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	rows, err := r.DB.Query(ctx, `
        SELECT `+campaignColumns+`
        FROM email_campaigns c
        WHERE c.tenant_id = $1
        ORDER BY c.created_at DESC
    `, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to query campaigns: %w", err)
	}
	defer rows.Close()

	var campaigns []*model.EmailCampaign
	for rows.Next() {
		c, err := scanCampaign(rows)
		if err != nil {
			return nil, fmt.Errorf("failed to scan campaign row: %w", err)
		}
		campaigns = append(campaigns, c)
	}
	return campaigns, nil
}

// Tickets lists the authenticated tenant's tickets for the inbox
func (r *queryResolver) Tickets(ctx context.Context, status *string, priority *string, search *string) ([]*model.Ticket, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	opts := services.ListTicketsOptions{}
	if status != nil {
		opts.Status = *status
	}
	if priority != nil {
		opts.Priority = *priority
	}
	if search != nil {
		opts.Search = *search
	}

	tickets, err := r.TicketService.ListTickets(ctx, tenantID, opts)
	if err != nil {
		return nil, err
	}

	result := []*model.Ticket{}
	for _, t := range tickets {
		result = append(result, ticketToGraphQL(t))
	}
	return result, nil
}

// Ticket fetches a single tenant-owned ticket with its full message thread
func (r *queryResolver) Ticket(ctx context.Context, id uuid.UUID) (*model.Ticket, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	t, err := r.TicketService.GetTicketWithMessages(ctx, tenantID, id.String())
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Unknown or foreign ticket — the schema allows a null ticket
			return nil, nil
		}
		return nil, err
	}
	return ticketToGraphQL(t), nil
}

// CannedResponses lists the tenant's quick-reply templates
func (r *queryResolver) CannedResponses(ctx context.Context) ([]*model.CannedResponse, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	rows, err := r.DB.Query(ctx, `
        SELECT id, name, shortcut, body
        FROM canned_responses
        WHERE tenant_id = $1
        ORDER BY name
    `, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to query canned responses: %w", err)
	}
	defer rows.Close()

	result := []*model.CannedResponse{}
	for rows.Next() {
		var c model.CannedResponse
		var id string
		if err := rows.Scan(&id, &c.Name, &c.Shortcut, &c.Body); err != nil {
			return nil, fmt.Errorf("failed to scan canned response: %w", err)
		}
		c.ID = parseUUID(id)
		result = append(result, &c)
	}
	return result, nil
}

// SupportMetrics aggregates ticket KPIs for the metrics dashboard
func (r *queryResolver) SupportMetrics(ctx context.Context) (*model.SupportMetrics, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	m := &model.SupportMetrics{
		TicketsByDay:      []*model.TicketsByDay{},
		TicketsByStatus:   []*model.TicketsByStatus{},
		TicketsByPriority: []*model.TicketsByPriority{},
	}

	// Scalar KPIs in one pass. Breach rate counts SLA-tracked tickets whose
	// first response came late — or hasn't come and the deadline has passed.
	err := r.DB.QueryRow(ctx, `
        SELECT
            COUNT(*) FILTER (WHERE status = 'open'),
            COALESCE(AVG(EXTRACT(EPOCH FROM (first_response_at - created_at)) / 3600.0)
                     FILTER (WHERE first_response_at IS NOT NULL), 0),
            COALESCE(AVG(EXTRACT(EPOCH FROM (resolved_at - created_at)) / 3600.0)
                     FILTER (WHERE resolved_at IS NOT NULL), 0),
            COALESCE(
                COUNT(*) FILTER (WHERE sla_first_response_at IS NOT NULL AND (
                    (first_response_at IS NOT NULL AND first_response_at > sla_first_response_at) OR
                    (first_response_at IS NULL AND sla_first_response_at < NOW())
                ))::float
                / NULLIF(COUNT(*) FILTER (WHERE sla_first_response_at IS NOT NULL), 0),
            0)
        FROM tickets
        WHERE tenant_id = $1
    `, tenantID).Scan(
		&m.OpenTickets, &m.AvgFirstResponseHours, &m.AvgResolutionHours, &m.SLABreachRate,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to query support KPIs: %w", err)
	}

	// Last 7 days, zero-filled so the chart always shows a full week
	dayRows, err := r.DB.Query(ctx, `
        SELECT to_char(d.day, 'Dy') AS date, COUNT(t.id)
        FROM generate_series(CURRENT_DATE - INTERVAL '6 days', CURRENT_DATE, '1 day') AS d(day)
        LEFT JOIN tickets t
            ON t.tenant_id = $1 AND t.created_at::date = d.day::date
        GROUP BY d.day
        ORDER BY d.day
    `, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to query tickets by day: %w", err)
	}
	defer dayRows.Close()
	for dayRows.Next() {
		var row model.TicketsByDay
		if err := dayRows.Scan(&row.Date, &row.Count); err != nil {
			return nil, fmt.Errorf("failed to scan tickets by day: %w", err)
		}
		m.TicketsByDay = append(m.TicketsByDay, &row)
	}

	statusRows, err := r.DB.Query(ctx, `
        SELECT status, COUNT(*)
        FROM tickets
        WHERE tenant_id = $1
        GROUP BY status
        ORDER BY COUNT(*) DESC
    `, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to query tickets by status: %w", err)
	}
	defer statusRows.Close()
	for statusRows.Next() {
		var row model.TicketsByStatus
		if err := statusRows.Scan(&row.Status, &row.Count); err != nil {
			return nil, fmt.Errorf("failed to scan tickets by status: %w", err)
		}
		m.TicketsByStatus = append(m.TicketsByStatus, &row)
	}

	priorityRows, err := r.DB.Query(ctx, `
        SELECT priority, COUNT(*)
        FROM tickets
        WHERE tenant_id = $1
        GROUP BY priority
        ORDER BY COUNT(*) DESC
    `, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to query tickets by priority: %w", err)
	}
	defer priorityRows.Close()
	for priorityRows.Next() {
		var row model.TicketsByPriority
		if err := priorityRows.Scan(&row.Priority, &row.Count); err != nil {
			return nil, fmt.Errorf("failed to scan tickets by priority: %w", err)
		}
		m.TicketsByPriority = append(m.TicketsByPriority, &row)
	}

	return m, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
